services:
  builder:
    build:
      context: ./
      args:
        - OS_CODENAME=${OS_CODENAME}
    image: guacamole-server-builder:${OS_CODENAME}
    container_name: guacamole-server-builder
    environment:
      - GUACAMOLE_VERSION=1.5.5
      - GUACAMOLE_REVISION=2
      - MAINTAINER=Apache Guacamole
      - OS_CODENAME=${OS_CODENAME}
    volumes:
      - ./work:/work
